#ifndef ARM_ALLOW_MULTI_CORE
#define ARM_ALLOW_MULTI_CORE
#endif

#include <circle/types.h>
#include <circle/sysconfig.h>
#include <circle/startup.h>
#include <circle/actled.h>
#include <circle/koptions.h>
#include <circle/devicenameservice.h>
#include <circle/screen.h>
#include <circle/serial.h>
#include <circle/logger.h>
#include <circle/interrupt.h>
#include <circle/timer.h>
#include <circle/alloc.h>
#include <circle/memory.h>      // Required for CMemorySystem
#include <circle/multicore.h>

// Embedded image header generated by xxd
#include "image_data.h"

class CKernel : public CMultiCoreSupport
{
public:
    CKernel(void)
        : CMultiCoreSupport(&m_Memory), // Pass CMemorySystem to CMultiCoreSupport constructor
          m_Options(),
          m_DeviceNameService(),
          m_Memory(),                   // Initialize memory system
          m_Interrupt(),
          m_Timer(&m_Interrupt),
          m_Logger(m_Options.GetLogLevel(), &m_Timer),
          m_Serial(&m_Interrupt),
          m_Graphics(1024, 768)
    {
    }

    bool Initialize(void)
    {
        // 1. CMemorySystem is already initialized by its constructor during CKernel instantiation.
        
        // 2. Initialize hardware devices
        if (!m_Interrupt.Initialize()) return false;
        if (!m_Timer.Initialize()) return false;
        if (!m_Serial.Initialize(115200)) return false;
        if (!m_Logger.Initialize(&m_Serial)) return false;

        m_Logger.Write("CKernel", LogNotice, "Booting Circle on Raspberry Pi 4 (QEMU)...");

        if (!m_Graphics.Initialize())
        {
            m_Logger.Write("CKernel", LogError, "Graphics initialization failed!");
            return false;
        }

        // 3. Initialize secondary cores (Cores 1-3)
        if (!CMultiCoreSupport::Initialize())
        {
            m_Logger.Write("CKernel", LogError, "Multi-core initialization failed!");
            return false;
        }

        return true;
    }

    void DrawRawToFramebuffer(const unsigned char* rawData, u32 width, u32 height)
    {
        CBcmFrameBuffer* pFB = m_Graphics.GetFrameBuffer();
        if (!pFB)
        {
            m_Logger.Write("CKernel", LogError, "Framebuffer driver is NULL!");
            return;
        }

        u32 depth       = pFB->GetDepth();
        u32 screenPitch = pFB->GetPitch();

        // 64-bit uintptr types prevent pointer-cast compiler warnings
        u32 gpuAddr  = reinterpret_cast<u32>(pFB->GetBuffer());
        u32 physAddr = gpuAddr & ~0xC0000000UL;

        u8* fbBase = reinterpret_cast<u8*>(physAddr);

        m_Logger.Write("CKernel", LogNotice, 
                       "Direct VRAM Write -> Depth: %u bpp, Pitch: %u, Phys Addr: %p", 
                       depth, screenPitch, reinterpret_cast<void*>(physAddr));

        if (depth == 32)
        {
            for (u32 y = 0; y < height; ++y)
            {
                u32* row32 = reinterpret_cast<u32*>(fbBase + (y * screenPitch));
                for (u32 x = 0; x < width; ++x)
                {
                    u32 srcIdx = (y * width + x) * 3;
                    u8 r = rawData[srcIdx];
                    u8 g = rawData[srcIdx + 1];
                    u8 b = rawData[srcIdx + 2];

                    row32[x] = (0xFF << 24) | ((u32)r << 16) | ((u32)g << 8) | (u32)b;
                }
            }
        }
        else if (depth == 16)
        {
            for (u32 y = 0; y < height; ++y)
            {
                u16* row16 = reinterpret_cast<u16*>(fbBase + (y * screenPitch));
                for (u32 x = 0; x < width; ++x)
                {
                    u32 srcIdx = (y * width + x) * 3;
                    u8 r = rawData[srcIdx];
                    u8 g = rawData[srcIdx + 1];
                    u8 b = rawData[srcIdx + 2];

                    row16[x] = static_cast<u16>(((r & 0xF8) << 8) | 
                                                ((g & 0xFC) << 3) | 
                                                 (b >> 3));
                }
            }
        }

        CleanDataCache();
    }

    void Run(unsigned nCore) override
    {
        if (nCore == 0)
        {
            m_Logger.Write("CKernel", LogNotice, "Core 0 active. Displaying embedded image...");
            DrawRawToFramebuffer(image_raw, 256, 256);

            while (true)
            {
                // Core 0 main loop
            }
        }
        else
        {
            m_Logger.Write("CKernel", LogNotice, "Secondary Core %u booted and standing by.", nCore);

            // Cores 1, 2, and 3 stay in an idle loop waiting for work/pthreads
            while (true)
            {
                asm volatile("wfe"); // Wait For Event (low-power CPU idle)
            }
        }
    }

private:
    CKernelOptions m_Options;
    CDeviceNameService m_DeviceNameService;
    CMemorySystem m_Memory; // Member memory manager for heap and multi-core stacks
    CInterruptSystem m_Interrupt;
    CTimer m_Timer;
    CLogger m_Logger;
    CSerialDevice m_Serial;
    CScreenDevice m_Graphics;
};

int main(void)
{
    CKernel Kernel;
    if (Kernel.Initialize()) 
    { 
        Kernel.Run(0); 
    }
    return 0;
}