#include <circle/types.h>
#include <circle/sysconfig.h>
#include <circle/startup.h>
#include <circle/actled.h>
#include <circle/koptions.h>
#include <circle/devicenameservice.h>
#include <circle/screen.h>
#include <circle/serial.h>
#include <circle/logger.h>
#include <circle/interrupt.h>
#include <circle/timer.h>

// Embedded image header generated by xxd
#include "image_data.h"

class CKernel
{
public:
    CKernel(void)
        : m_Options(),
          m_DeviceNameService(),
          m_Graphics(1024, 768),
          m_Serial(&m_Interrupt),
          m_Logger(m_Options.GetLogLevel(), &m_Timer),
          m_Interrupt(),
          m_Timer(&m_Interrupt)
    {
    }

    bool Initialize(void)
    {
        m_Interrupt.Initialize();
        m_Timer.Initialize();

        m_Serial.Initialize(115200);
        m_Logger.Initialize(&m_Serial);

        m_Logger.Write("CKernel", LogNotice, "Booting Circle on Raspberry Pi 4 (QEMU)...");

        if (!m_Graphics.Initialize())
        {
            m_Logger.Write("CKernel", LogError, "Graphics initialization failed!");
            return false;
        }

        return true;
    }

    void DrawRawRGB(const unsigned char* data, u32 width, u32 height) 
    {
        for (u32 y = 0; y < height; ++y)
        {
            for (u32 x = 0; x < width; ++x)
            {
                u32 index = (y * width + x) * 3;

                u8 r = data[index];
                u8 g = data[index+1];
                u8 b = data[index+2];
                u32 color = (0xFF << 24) | ((u32)r << 16) | ((u32)g << 8) | (u32)b;
                m_Graphics.SetPixel(x, y, color);
            }
        }
    }

    void Run(void)
    {
        m_Logger.Write("CKernel", LogNotice, "Displaying embedded image...");

        CBcmFrameBuffer* pFB = m_Graphics.GetFrameBuffer();

        u32 depth       = pFB->GetDepth(); 
        u32 screenPitch = pFB->GetPitch(); // Stride in bytes
        
        // Convert GPU bus address to ARM physical RAM pointer
        u32 gpuAddr  = reinterpret_cast<u32>(pFB->GetBuffer());
        u32 physAddr = gpuAddr & ~0xC0000000UL;

        m_Logger.Write("CKernel", LogNotice, 
                    "Screen Depth: %u bpp, Pitch: %u, VRAM Addr: %p", 
                    depth, screenPitch, physAddr);

        DrawRawRGB(image_raw, 256, 256);

        while (true)
        {
            // Main execution loop
        }

    }

private:
    CKernelOptions m_Options;
    CDeviceNameService m_DeviceNameService;
    CScreenDevice m_Graphics;
    CSerialDevice m_Serial;
    CLogger m_Logger;
    CInterruptSystem m_Interrupt;
    CTimer m_Timer;
};

int main(void)
{
    CKernel Kernel;
    if (Kernel.Initialize()) { Kernel.Run(); }
    return 0;
}

/*int main(void)
{
    volatile unsigned int * const UART0_DR = (unsigned int *)0xFE201000;
    volatile unsigned int * const UART0_FR = (unsigned int *)0xFE201018;

    auto write_char = [&](char c) {
        // Wait while Transmit FIFO is Full (TXFF bit 5 is set)
        while (*UART0_FR & (1 << 5)) {
            asm volatile("nop");
        }
        *UART0_DR = c;
    };

    const char *msg = "\r\n*** HELLO FROM RASPBERRY PI 4 BARE-METAL ***\r\n";
    for (const char *p = msg; *p; p++) {
        write_char(*p);
    }

    while (1) {}
}*/